type Station {
  id: ID!
  name: String!
  address: String
  city: String
  coordinates: Coordinates!
  
  # Available connectors
  connectors: [Connector!]!

  # Metadata
  accessType: String
  isSuperFast: Boolean
  lastUpdated: String
  
  # Optional distance field for nearby queries
  distance: Float
}

type Connector {
  type: ConnectorType!
  powerKw: Float!
  status: ConnectorStatus!
  statusCode: String!
}


enum ConnectorType {
  CCS      
  CHADEMO  
  MENNEKES 
  SCHUKO   
}

enum ConnectorStatus {
  AVAILABLE    
  OCCUPIED     
  UNAVAILABLE  
}

type StationsResponse {
  stations: [Station!]!
  total: Int!
}

input LocationInput {
  coordinates: CoordinatesInput!
  radiusKm: Float
}

input BoundsInput {
  north: Float!
  south: Float!
  east: Float!
  west: Float!
}

extend type Query {
  """
    Returns all the stations avaiable in the system including their live status
  """
  stations: StationsResponse!
  """
    Returns a specific station given his unique id
  """
  station(id: ID!): Station
  """
    Given a coordinate (in this order: latitude, longitude) and a radius (in km)
    return all stations that are within that radius
  """
  nearbyStations(location: LocationInput!): [Station!]!
  
  """ 
    These queries are not implemented yet
  """
  stationsInBounds(bounds: BoundsInput!): [Station!]!
  stationsByCity(city: String!): [Station!]!
  stationsByAdress(address: String!): [Station!]!
}

