type friendship{
    nickname1: String!
    nickname2: String!
}

type friend{
    name: String!
}

type blockedUser{
    blocked: String!
}

extend type Query{
    ListFriends(nickname: String!): [friend!]
    AllFriends: [friendship!]
    BlockList: [blockedUser!]
}

extend type Mutation {
    AddFriendship(nickname1: String!, nickname2: String!): friendship!
    RemoveFriendship(nickname1: String!, nickname2: String!): Boolean!
    BlockUser(nickname: String!): Boolean!
    UnBlockUser(nickname: String!): Boolean!
}