"""
Enumeración de los modos de transporte preferidos por el usuario.
"""
enum Mode {
  CAR
  BIKE
}

enum Language {
  ESP
  CAT
  ENG
}

"""
Representa un usuario registrado en el sistema.
Contiene información de perfil y preferencias de transporte.
"""
type User {
  email: String!
  name: String
  nickname: String
  photo: String
  birthDate: String
  phoneNumber: String
  preferredMode: Mode
  preferredLanguage: Language
  bioDescription: String
  createdAt: String
  regWithGoogle: Boolean!
  isBanned: Boolean!
  banInfo: BanInfo
  statistics: RankingStats
}

type ExistsUser {
  exists: Boolean!
  isRegWithGoogle: Boolean
}

"""
Input para crear un nuevo usuario.
birthDate en formato DD-MM-AAAA
preferredLanguage es opcional, por defecto ESP. Se espera: ESP, CAT o ENG
"""
input CreateUserInput {
  email: String!
  name: String!
  nickname: String!
  photo: String
  phoneNumber: String
  preferredMode: Mode!
  preferredLanguage: Language
  birthDate: String
  bioDescription: String
  regWithGoogle: Boolean!
}

"""
Input para actualizar información del usuario.
Todos los campos son opcionales.
"""
input UserUpdateInput {
  name: String
  nickname: String
  phoneNumber: String
  bioDescription: String
  preferredMode: Mode
  preferredLanguage: Language
  birthDate: String
  photo: String
}

extend type Query {
  """
  Obtiene los datos del usuario de la sesión actual.
  Requiere token en header: Authorization: Bearer <token>
  """
  me: User

  """
  Obtiene un usuario por email.
  """
  User(email: String!): User

  """
  Lista todos los usuarios.
  """
  Users: [User!]!

  """
  Obtiene el/los usuario/s con matching parcial tales que empiezan por el parámetro nickname. 
  Null, si no hay matching.
  """
  UsersByNickname(nickname: String!): [User!]!

  """
  Verifica si un usuario con el email dado existe.
  Devuelve un objeto con 'exists' que representa la existencia y 'isRegWithGoogle' donde si existe, dice cómo se ha registrado, null si no existe.
  """
  ExistsUser(email:String!): ExistsUser!

  """
  Obtiene el historial de las últimas 5 búsuqedas del usuario autenticado.
  """
  UsersSearchHistory: [String!]!
}

extend type Mutation {
  """
  Actualiza los datos del usuario autenticado.
  Usa email del token.
  """
  updateMe(
    name: String
    nickname: String
    phoneNumber: String
    bioDescription: String
    preferredMode: Mode
    preferredLanguage: Language
    birthDate: String
    photo: String
  ): User!

  """
  Actualiza cualquier usuario (admin).
  """
  updateUser(email: String!, name: String, preferredMode: Mode): User!

  """
  Crea un nuevo usuario.
  """
  createUser(createInfo: CreateUserInput!): User!

  """
  Elimina un usuario.
  """
  deleteUser(email: String!): Boolean!

  """
  Elimina tu cuenta.
  """
  deleteMe: Boolean!

  """
  Borrar foto de perfil
  """
  deleteProfilePhoto: User!

  """
  Banear a un usuario
  """
  banUser(
    email: String!
    reason: String!
    description: String
    duration: String!
  ): User

  """
  Desbanear a un usuario
  """
  unbanUser(email: String!): User
}

type BanInfo {
  reason: String!
  description: String
  duration: String!
  createdAt: String!
}
