name: Despliegue Docker EC2 Automático

on:
  workflow_run:
    workflows: ["CI Backend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Echo workflow_run info
        run: |
          echo "Workflow run head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Definir servicio según rama
        id: vars
        run: |
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          if [ "$BRANCH" == "main" ]; then
            echo "servicio=pro-backend" >> $GITHUB_OUTPUT
            echo "git_branch=main" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == release/* ]]; then
            echo "servicio=pre-backend" >> $GITHUB_OUTPUT
            echo "git_branch=$BRANCH" >> $GITHUB_OUTPUT
          elif [ "$BRANCH" == "dev" ]; then
            echo "servicio=test-backend" >> $GITHUB_OUTPUT
            echo "git_branch=dev" >> $GITHUB_OUTPUT
          else
            echo "servicio=none" >> $GITHUB_OUTPUT
            echo "git_branch=none" >> $GITHUB_OUTPUT
          fi

      - name: Desplegar servicio en EC2
        if: steps.vars.outputs.servicio != 'none'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_BRANCH: ${{ steps.vars.outputs.git_branch }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ubuntu/BeMotion
          docker-compose stop ${{ steps.vars.outputs.servicio }}
          docker-compose rm -f ${{ steps.vars.outputs.servicio }}
          docker-compose build --no-cache --build-arg GITHUB_TOKEN=${GH_TOKEN} --build-arg GIT_BRANCH=${GIT_BRANCH} ${{ steps.vars.outputs.servicio }}
          docker-compose up -d --no-deps ${{ steps.vars.outputs.servicio }}
          EOF
