name: Despliegue Docker EC2 Automático

on:
  push:
    branches:
      
main
dev
'release/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      
name: Definir servicio según rama
      id: vars
      run: |
        if [ "${GITHUB_REF##/}" == "main" ]; then
          echo "servicio=pro-backend" >> $GITHUB_OUTPUT
          echo "git_branch=main" >> $GITHUB_OUTPUT
        elif [[ "${GITHUB_REF}" == refs/heads/release/ ]]; then
          echo "servicio=pre-backend" >> $GITHUB_OUTPUT
          echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        elif [ "${GITHUB_REF##*/}" == "dev" ]; then
          echo "servicio=test-backend" >> $GITHUB_OUTPUT
          echo "git_branch=dev" >> $GITHUB_OUTPUT
        else
          echo "servicio=none" >> $GITHUB_OUTPUT
          echo "git_branch=none" >> $GITHUB_OUTPUT
        fi

      
name: Desplegar servicio en EC2
      if: steps.vars.outputs.servicio != 'none'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_BRANCH: ${{ steps.vars.outputs.git_branch }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
        cd /home/ubuntu/BeMotion
        docker-compose build --no-cache \--build-arg GITHUB_TOKEN=${GH_TOKEN} \--build-arg GIT_BRANCH=${GIT_BRANCH} \${{ steps.vars.outputs.servicio }}
        docker-compose up -d --no-deps ${{ steps.vars.outputs.servicio }}
        EOF
